name: flutter_mcp_server
description: Flutter implementation of Model Context Protocol (MCP) server for exposing data and functionality to MCP clients
version: 0.1.4
homepage: https://github.com/app-appplayer/flutter_mcp_server

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  mcp_server:
    path: ../mcp_server
  flutter_mcp_common:
    path: ../flutter_mcp_common
  shared_preferences: ^2.5.2
  provider: ^6.0.5
  rxdart: ^0.27.7
  equatable: ^2.0.5
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  plugin:
    platforms:
      android:
        package: app.appplayer.flutter_mcp_server
        pluginClass: FlutterMcpServerPlugin
      ios:
        pluginClass: FlutterMcpServerPlugin
      web:
        pluginClass: FlutterMcpServerWeb
        fileName: flutter_mcp_server_web.dart
      macos:
        pluginClass: FlutterMcpServerPlugin
      windows:
        pluginClass: FlutterMcpServerPluginCApi
      linux:
        pluginClass: FlutterMcpServerPlugin
